services:
  web:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/browser0
      - NODE_ENV=production
      - BROWSERIZE_API_KEY=${BROWSERIZE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=browser0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      # Database data stored in local ./postgres_data folder
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 